FROM ubuntu:20.04
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update -y && apt-get install -y apt-utils curl vim sudo
RUN curl -sL https://deb.nodesource.com/setup_16.x  | bash -
RUN apt-get -y install nodejs

WORKDIR /server

COPY . /server

RUN npm install -g npm
RUN npm install
RUN npm run build

RUN ["chmod", "+x", "./input.sh"]
RUN ["chmod", "+x", "./agent-install.sh"]

EXPOSE 3000
ENTRYPOINT ["sh", "./input.sh"]
