FROM arm32v7/node:16.3.0

RUN apt-get update -y && apt-get install -y apt-utils curl vim sudo

WORKDIR /server

COPY . /server

RUN npm install -g npm
RUN npm install
RUN npm run build

RUN ["chmod", "+x", "./input.sh"]
RUN ["chmod", "+x", "./agent-install.sh"]

EXPOSE 3000
ENTRYPOINT ["sh", "./input.sh"]
