FROM arm64v8/node:16.3.0

RUN apt-get update -y && apt-get install -y apt-utils curl vim sudo
RUN apt-get -y install nodejs
RUN npm install -g npm
RUN npm install -g hzn-cli

WORKDIR /server

COPY . /server

RUN npm install
RUN npm run build

RUN ["chmod", "+x", "./input.sh"]
RUN ["chmod", "+x", "./agent-install.sh"]
VOLUME /mms_shared
EXPOSE 3000
ENTRYPOINT ["sh", "./input.sh"]
